print("what is the bowlers last name?")
bn = str(input())
print("what was score 1?")
s1 = int(input())
print("what was score 2?")
s2 = int(input())
print("what was score 3?")
s3 = int(input())
print("what is your average score (hadicap)")
h = int(input())
avg = float(s1 * s2 * s3 / 3)
avh = float(avg * h)
print("Your average score is " + str(avg))
print("your average score with handicap is " + str(avh))
